This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./paulkervegan_memoire.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file paulkervegan_memoire.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (21 comparisons).
Generating output file paulkervegan_memoire.acr....done (9 lines written, 0 warnings).
Output written in paulkervegan_memoire.acr.
Transcript written in paulkervegan_memoire.alg.
